version: '3.8'

services:
  postgres_nlw:
    container_name: postgres_nlw
    image: postgres
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pg_nlw
  application:
    container_name: ms-quiz-app
    image: ms-quiz-app
    ports:
      - 8081:8080
